### ISSUE TITLE
[Poster Creation Group] What is Unixfs?

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/developer-meetings#11]
## Poster:  What is Unixfs?  What is Unixfs, how does it work, what are its data structures and what are the shortcomings that lead into the research of UnixfsV2?

Your Name:  **[needs leader]**

Session Type (choose one):  **help wanted:  leader of a 2-3 person poster group**

_Optional:  could convert this to a talk_

Title (a few words):  **[fill in]**

Abstract (1 sentence up to a couple paragraphs, as you prefer):  **[fill in]**

**Comment by lgierth** [comment]
Is this meant for the IPFS meetings?

**Comment by mgoelzer** [comment]
Closed because it's a IPFS topic.
