### ISSUE TITLE
[Poster Creation Group] How does Bitswap work?

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/developer-meetings#17]
## Poster:  How does Bitswap work?

Your Name:  **[needs leader]**

Session Type (choose one):  **help wanted:  leader of a 2-3 person poster group**

_Optional:  could convert this to a talk_

Title (a few words):  **[fill in]**

Abstract (1 sentence up to a couple paragraphs, as you prefer):  **[fill in]**

**Comment by lgierth** [comment]
Is this meant for the IPFS meetings?

**Comment by mgoelzer** [comment]
@lgierth Probably, yes.  Can you think of a good libp2p topic to replace this?  Else, we can close this issue.

**Comment by mgoelzer** [comment]
Closing b/c more appropriate as an IPLD or IPFS topic.
