### ISSUE TITLE
[Protocol Design] Scaling Content Routing

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/developer-meetings#21]
## [Protocol Design] Scaling Content Routing

Your Name:  @whyrusleeping

Session Type (choose one):  design session

Title (a few words):  Scaling Content Routing

Abstract (1 sentence up to a couple paragraphs, for Sched):  Currently ipfs uses a DHT for all content routing. This works quite well for many use cases and is generally reliable, fast, and durable. The problem we are now facing is that it does not scale well. Sending out provider records for every single block of every file to the DHT uses an obscene amount of bandwidth, not to mention the increased CPU and memory load. To continue improving ipfs, we need to find a better solution.

**Comment by mgoelzer** [comment]
Related issue https://github.com/ipfs/notes/issues/162

**Comment by diasdavid** [comment]
Merged with https://github.com/libp2p/developer-meetings/issues/7
