### ISSUE TITLE
[Protocol Design] IPRS

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/developer-meetings#22]
## [Protocol Design] IPRS - the "right" way to do signed address records, let's design it!

Your Name:  @whyrusleeping (or anyone who wants to claim this, just coordinate with why who suggested it)

Session Type (choose one):  leader/moderator of a design session

Title (a few words):  IPRS -  the "right" way to do signed address records

Abstract (1 sentence up to a couple paragraphs, for Sched):  Many applications wanting to build on top of libp2p will need a certified record store system. IPFS currently uses IPNS, which is relatively inflexible. Let's sit down and get a solid design for IPRS so that we can move towards getting it implemented.

**Comment by diasdavid** [comment]
Please drop your notes to https://github.com/libp2p/developer-meetings/tree/master/notes
