### ISSUE TITLE
[Protocol Design] placeholder for stebalien proposal on some protocol issues

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/developer-meetings#5]
## Placeholder (@Stebalien will fill this in when he has time)

Name:  @Stebalien 

Length (choose one):  90 minute discussion meeting (40 + break + 40)

Title (~1-7 words):  **[fill in]**

Abstract (1 sentence up to a couple paragraphs, as you prefer):  **[fill in]**

**Comment by mgoelzer** [comment]
@Stebalien I'm closing this in favor of #6.  But if you have a second topic for protocol design discussion that you want to lead, just reopen.

**Comment by Stebalien** [comment]
(I wanted a full protocol design and proposal before filling this in but, in retrospect, that would have been overkill and completely unnecessary).

**Comment by mgoelzer** [comment]
Awesome - this is a great topic.  Glad you thought of it.

**Comment by diasdavid** [comment]
Please drop your notes to https://github.com/libp2p/developer-meetings/tree/master/notes
